# factory/tasks/_provision.yml
version: '3'
tasks:
  provision:
    desc: "GUIDE: Shows setup checklist for cloud infrastructure."
    silent: true
    cmds:
      - |
        gum style --border normal --margin "1" --padding "1 2" --border-foreground 212 "This command is a placeholder and is not yet implemented."
