# factory/tasks/_test.yml
version: '3'
tasks:
  test:
    desc: "ACTION: Interactively run tests (unit, race, integration) for all Go modules."
    long: "Runs a script that provides a menu to select the desired test suite and then executes it for all Go modules found in the project."
    silent: true
    cmds:
      - ./factory/scripts/test.sh {{.CLI_ARGS}}